### PR TITLE
Add app name

### PR DESCRIPTION
**Pull request by kocunop**
add optional app name to setting.

Fix double quotes on save from django admin.

### CODE REVIEW

**Review by mikeengland — APPROVED** [review]
Thanks for your contribution @kocunop! I'll try and create a new release ASAP.

**Comment by mikeengland** [comment]
@kocunop it looks like your PR was missing a migration (for some reason the build did not run on this PR branch, I'll look into that). Would you mind adding this?

**Comment by mikeengland** [comment]
Fixed in v3.2.0

**Comment by kocunop** [comment]
there really was no migration, thanks for fix.

**Pull request merged**
